name: "kubesealer: Lint"
description: GitHub Action that lints a golang based repository via [action-pre-commit](https://github.com/open-turo/action-pre-commit)
inputs:
  github-personal-access-token:
    required: true
    description: Token used to communicate with GitHub API that can create PRs
  op-token:
    required: true
    description: Token used to communicate with 1Password Connect API
  op-credentials-json-base64:
    required: true
    description: Base64 encoded JSON containing credentials for 1Password Connect API
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: run sync
      uses: turo/actions-kubesealer/run-sync@v1
      with:
        op-token: ${{ inputs.op-token }}
        op-credentials-json-base64: ${{ inputs.op-credentials-json-base64 }}

    - name: diff
      shell: bash
      run: git diff

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      id: cpr
      with:
        token: ${{ inputs.github-personal-access-token }}
        branch: kubesealer-main
        base: main
        commit-message: "fix(kubesealer): updates sealed secrets - automated action"
        title: "fix(kubesealer): updates sealed secrets - automated action"
        body: |
          Update sealed secrets using kubesealer
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          kubesealer

    - name: Check outputs
      shell: bash
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
